# Make sure to add exceptions in utility.py - selectMeshChildrenOnly
ootEnumEmptyType = [
    ("None", "None", "None"),
    ("Scene", "Scene", "Scene"),
    ("Room", "Room", "Room"),
    ("Actor", "Actor", "Actor"),
    ("Transition Actor", "Transition Actor", "Transition Actor"),
    ("Entrance", "Entrance", "Entrance"),
    ("Water Box", "Water Box", "Water Box"),
    ("Cull Group", "Cull Group", "Cull Group"),
    ("LOD", "LOD Group", "LOD Group"),
    ("Cutscene", "Cutscene", "Cutscene"),
    # ('Camera Volume', 'Camera Volume', 'Camera Volume'),
]

ootRegisterQueue = []  # is this a good idea?

ootEnumHeaderMenu = [
    ("Child Night", "Child Night", "Child Night"),
    ("Adult Day", "Adult Day", "Adult Day"),
    ("Adult Night", "Adult Night", "Adult Night"),
    ("Cutscene", "Cutscene", "Cutscene"),
]

# The order of this list matters (normal OoT scene order as defined by ``scene_table.h``)
ootEnumSceneID = [
    ("Custom", "Custom", "Custom"),
    ("SCENE_YDAN", "Inside the Deku Tree (Ydan)", "Ydan"),
    ("SCENE_DDAN", "Dodongo's Cavern (Ddan)", "Ddan"),
    ("SCENE_BDAN", "Inside Jabu Jabu's Belly (Bdan)", "Bdan"),
    ("SCENE_BMORI1", "Forest Temple (Bmori1)", "Bmori1"),
    ("SCENE_HIDAN", "Fire Temple (Hidan)", "Hidan"),
    ("SCENE_MIZUSIN", "Water Temple (Mizusin)", "Mizusin"),
    ("SCENE_JYASINZOU", "Spirit Temple (Jyasinzou)", "Jyasinzou"),
    ("SCENE_HAKADAN", "Shadow Temple (Hakadan)", "Hakadan"),
    ("SCENE_HAKADANCH", "Bottom of the Well (Hakadanch)", "Hakadanch"),
    ("SCENE_ICE_DOUKUTO", "Ice Cavern (Ice Doukuto)", "Ice Doukuto"),
    ("SCENE_GANON", "Ganon's Tower (Ganon)", "Ganon"),
    ("SCENE_MEN", "Gerudo Training Ground (Men)", "Men"),
    ("SCENE_GERUDOWAY", "Thieves' Hideout (Gerudoway)", "Gerudoway"),
    ("SCENE_GANONTIKA", "Inside Ganon's Castle (Ganontika)", "Ganontika"),
    ("SCENE_GANON_SONOGO", "Ganon's Tower (Collapsing) (Ganon Sonogo)", "Ganon Sonogo"),
    ("SCENE_GANONTIKA_SONOGO", "Inside Ganon's Castle (Collapsing) (Ganontika Sonogo)", "Ganontika Sonogo"),
    ("SCENE_TAKARAYA", "Treasure Chest Shop (Takaraya)", "Takaraya"),
    ("SCENE_YDAN_BOSS", "Gohma's Lair (Ydan Boss)", "Ydan Boss"),
    ("SCENE_DDAN_BOSS", "King Dodongo's Lair (Ddan Boss)", "Ddan Boss"),
    ("SCENE_BDAN_BOSS", "Barinade's Lair (Bdan Boss)", "Bdan Boss"),
    ("SCENE_MORIBOSSROOM", "Phantom Ganon's Lair (Moribossroom)", "Moribossroom"),
    ("SCENE_FIRE_BS", "Volvagia's Lair (Fire Bs)", "Fire Bs"),
    ("SCENE_MIZUSIN_BS", "Morpha's Lair (Mizusin Bs)", "Mizusin Bs"),
    ("SCENE_JYASINBOSS", "Twinrova's Lair & Iron Knuckle Mini-Boss Room (Jyasinboss)", "Jyasinboss"),
    ("SCENE_HAKADAN_BS", "Bongo Bongo's Lair (Hakadan Bs)", "Hakadan Bs"),
    ("SCENE_GANON_BOSS", "Ganondorf's Lair (Ganon Boss)", "Ganon Boss"),
    ("SCENE_GANON_FINAL", "Ganondorf's Death Scene (Tower Escape Exterior) (Ganon Final)", "Ganon Final"),
    ("SCENE_ENTRA", "Market Entrance (Child - Day) (Entra)", "Entra"),
    ("SCENE_ENTRA_N", "Market Entrance (Child - Night) (Entra N)", "Entra N"),
    ("SCENE_ENRUI", "Market Entrance (Ruins) (Enrui)", "Enrui"),
    ("SCENE_MARKET_ALLEY", "Back Alley (Day) (Market Alley)", "Market Alley"),
    ("SCENE_MARKET_ALLEY_N", "Back Alley (Night) (Market Alley N)", "Market Alley N"),
    ("SCENE_MARKET_DAY", "Market (Child - Day) (Market Day)", "Market Day"),
    ("SCENE_MARKET_NIGHT", "Market (Child - Night) (Market Night)", "Market Night"),
    ("SCENE_MARKET_RUINS", "Market (Ruins) (Market Ruins)", "Market Ruins"),
    ("SCENE_SHRINE", "Temple of Time Exterior (Day) (Shrine)", "Shrine"),
    ("SCENE_SHRINE_N", "Temple of Time Exterior (Night) (Shrine N)", "Shrine N"),
    ("SCENE_SHRINE_R", "Temple of Time Exterior (Ruins) (Shrine R)", "Shrine R"),
    ("SCENE_KOKIRI_HOME", "Know-It-All Brothers' House (Kokiri Home)", "Kokiri Home"),
    ("SCENE_KOKIRI_HOME3", "Twins' House (Kokiri Home3)", "Kokiri Home3"),
    ("SCENE_KOKIRI_HOME4", "Mido's House (Kokiri Home4)", "Kokiri Home4"),
    ("SCENE_KOKIRI_HOME5", "Saria's House (Kokiri Home5)", "Kokiri Home5"),
    ("SCENE_KAKARIKO", "Carpenter Boss's House (Kakariko)", "Kakariko"),
    ("SCENE_KAKARIKO3", "Back Alley House (Man in Green) (Kakariko3)", "Kakariko3"),
    ("SCENE_SHOP1", "Bazaar (Shop1)", "Shop1"),
    ("SCENE_KOKIRI_SHOP", "Kokiri Shop (Kokiri Shop)", "Kokiri Shop"),
    ("SCENE_GOLON", "Goron Shop (Golon)", "Golon"),
    ("SCENE_ZOORA", "Zora Shop (Zoora)", "Zoora"),
    ("SCENE_DRAG", "Kakariko Potion Shop (Drag)", "Drag"),
    ("SCENE_ALLEY_SHOP", "Market Potion Shop (Alley Shop)", "Alley Shop"),
    ("SCENE_NIGHT_SHOP", "Bombchu Shop (Night Shop)", "Night Shop"),
    ("SCENE_FACE_SHOP", "Happy Mask Shop (Face Shop)", "Face Shop"),
    ("SCENE_LINK_HOME", "Link's House (Link Home)", "Link Home"),
    ("SCENE_IMPA", "Back Alley House (Dog Lady) (Impa)", "Impa"),
    ("SCENE_MALON_STABLE", "Stable (Malon Stable)", "Malon Stable"),
    ("SCENE_LABO", "Impa's House (Labo)", "Labo"),
    ("SCENE_HYLIA_LABO", "Lakeside Laboratory (Hylia Labo)", "Hylia Labo"),
    ("SCENE_TENT", "Carpenters' Tent (Tent)", "Tent"),
    ("SCENE_HUT", "Gravekeeper's Hut (Hut)", "Hut"),
    ("SCENE_DAIYOUSEI_IZUMI", "Great Fairy's Fountain (Upgrades) (Daiyousei Izumi)", "Daiyousei Izumi"),
    ("SCENE_YOUSEI_IZUMI_TATE", "Fairy's Fountain (Healing Fairies) (Yousei Izumi Tate)", "Yousei Izumi Tate"),
    ("SCENE_YOUSEI_IZUMI_YOKO", "Great Fairy's Fountain (Spells) (Yousei Izumi Yoko)", "Yousei Izumi Yoko"),
    ("SCENE_KAKUSIANA", "Grottos (Kakusiana)", "Kakusiana"),
    ("SCENE_HAKAANA", "Grave (Redead) (Hakaana)", "Hakaana"),
    ("SCENE_HAKAANA2", "Grave (Fairy's Fountain) (Hakaana2)", "Hakaana2"),
    ("SCENE_HAKAANA_OUKE", "Royal Family's Tomb (Hakaana Ouke)", "Hakaana Ouke"),
    ("SCENE_SYATEKIJYOU", "Shooting Gallery (Syatekijyou)", "Syatekijyou"),
    ("SCENE_TOKINOMA", "Temple of Time (Tokinoma)", "Tokinoma"),
    ("SCENE_KENJYANOMA", "Chamber of the Sages (Kenjyanoma)", "Kenjyanoma"),
    ("SCENE_HAIRAL_NIWA", "Castle Hedge Maze (Day) (Hairal Niwa)", "Hairal Niwa"),
    ("SCENE_HAIRAL_NIWA_N", "Castle Hedge Maze (Night) (Hairal Niwa N)", "Hairal Niwa N"),
    ("SCENE_HIRAL_DEMO", "Cutscene Map (Hiral Demo)", "Hiral Demo"),
    ("SCENE_HAKASITARELAY", "Dampé's Grave & Windmill (Hakasitarelay)", "Hakasitarelay"),
    ("SCENE_TURIBORI", "Fishing Pond (Turibori)", "Turibori"),
    ("SCENE_NAKANIWA", "Castle Courtyard (Nakaniwa)", "Nakaniwa"),
    ("SCENE_BOWLING", "Bombchu Bowling Alley (Bowling)", "Bowling"),
    ("SCENE_SOUKO", "Lon Lon Ranch House & Tower (Souko)", "Souko"),
    ("SCENE_MIHARIGOYA", "Guard House (Miharigoya)", "Miharigoya"),
    ("SCENE_MAHOUYA", "Granny's Potion Shop (Mahouya)", "Mahouya"),
    ("SCENE_GANON_DEMO", "Ganon's Tower Collapse & Battle Arena (Ganon Demo)", "Ganon Demo"),
    ("SCENE_KINSUTA", "House of Skulltula (Kinsuta)", "Kinsuta"),
    ("SCENE_SPOT00", "Hyrule Field (Spot00)", "Spot00"),
    ("SCENE_SPOT01", "Kakariko Village (Spot01)", "Spot01"),
    ("SCENE_SPOT02", "Graveyard (Spot02)", "Spot02"),
    ("SCENE_SPOT03", "Zora's River (Spot03)", "Spot03"),
    ("SCENE_SPOT04", "Kokiri Forest (Spot04)", "Spot04"),
    ("SCENE_SPOT05", "Sacred Forest Meadow (Spot05)", "Spot05"),
    ("SCENE_SPOT06", "Lake Hylia (Spot06)", "Spot06"),
    ("SCENE_SPOT07", "Zora's Domain (Spot07)", "Spot07"),
    ("SCENE_SPOT08", "Zora's Fountain (Spot08)", "Spot08"),
    ("SCENE_SPOT09", "Gerudo Valley (Spot09)", "Spot09"),
    ("SCENE_SPOT10", "Lost Woods (Spot10)", "Spot10"),
    ("SCENE_SPOT11", "Desert Colossus (Spot11)", "Spot11"),
    ("SCENE_SPOT12", "Gerudo's Fortress (Spot12)", "Spot12"),
    ("SCENE_SPOT13", "Haunted Wasteland (Spot13)", "Spot13"),
    ("SCENE_SPOT15", "Hyrule Castle (Spot15)", "Spot15"),
    ("SCENE_SPOT16", "Death Mountain Trail (Spot16)", "Spot16"),
    ("SCENE_SPOT17", "Death Mountain Crater (Spot17)", "Spot17"),
    ("SCENE_SPOT18", "Goron City (Spot18)", "Spot18"),
    ("SCENE_SPOT20", "Lon Lon Ranch (Spot20)", "Spot20"),
    ("SCENE_GANON_TOU", "Ganon's Castle Exterior (Ganon Tou)", "Ganon Tou"),
    ("SCENE_TEST01", "Jungle Gym (Test01)", "Test01"),
    ("SCENE_BESITU", "Ganondorf Test Room (Besitu)", "Besitu"),
    ("SCENE_DEPTH_TEST", "Depth Test (Depth Test)", "Depth Test"),
    ("SCENE_SYOTES", "Stalfos Mini-Boss Room (Syotes)", "Syotes"),
    ("SCENE_SYOTES2", "Stalfos Boss ROom (Syotes2)", "Syotes2"),
    ("SCENE_SUTARU", "Sutaru (Sutaru)", "Sutaru"),
    ("SCENE_HAIRAL_NIWA2", "Castle Hedge Maze (Early) (Hairal Niwa2)", "Hairal Niwa2"),
    ("SCENE_SASATEST", "Sasatest (Sasatest)", "Sasatest"),
    ("SCENE_TESTROOM", "Treasure Chest Room (Testroom)", "Testroom"),
]
