ootEnumRoomShapeType = [
    # ("Custom", "Custom", "Custom"),
    ("ROOM_SHAPE_TYPE_NORMAL", "Normal", "Normal"),
    ("ROOM_SHAPE_TYPE_IMAGE", "Image", "Image"),
    ("ROOM_SHAPE_TYPE_CULLABLE", "Cullable", "Cullable"),
]

ootEnumRoomMenu = [
    ("General", "General", "General"),
    ("Objects", "Objects", "Objects"),
    ("Alternate", "Alternate", "Alternate"),
]

ootEnumRoomMenuAlternate = [
    ("General", "General", "General"),
    ("Objects", "Objects", "Objects"),
]

ootEnumLinkIdle = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "Default", "Default"),
    ("0x01", "Sneezing", "Sneezing"),
    ("0x02", "Wiping Forehead", "Wiping Forehead"),
    ("0x04", "Yawning", "Yawning"),
    ("0x07", "Gasping For Breath", "Gasping For Breath"),
    ("0x09", "Brandish Sword", "Brandish Sword"),
    ("0x0A", "Adjust Tunic", "Adjust Tunic"),
    ("0xFF", "Hops On Epona", "Hops On Epona"),
]

ootEnumObjectID = [
    ("Custom", "Custom", "Custom"),
    ("OBJECT_HUMAN", "Human", "Human"),
    ("OBJECT_OKUTA", "Okuta", "Okuta"),
    ("OBJECT_CROW", "Crow", "Crow"),
    ("OBJECT_POH", "Poh", "Poh"),
    ("OBJECT_DY_OBJ", "Dy Obj", "Dy Obj"),
    ("OBJECT_WALLMASTER", "Wallmaster", "Wallmaster"),
    ("OBJECT_DODONGO", "Dodongo", "Dodongo"),
    ("OBJECT_FIREFLY", "Firefly", "Firefly"),
    ("OBJECT_BOX", "Box", "Box"),
    ("OBJECT_FIRE", "Fire", "Fire"),
    ("OBJECT_BUBBLE", "Bubble", "Bubble"),
    ("OBJECT_NIW", "Niw", "Niw"),
    ("OBJECT_TITE", "Tite", "Tite"),
    ("OBJECT_REEBA", "Reeba", "Reeba"),
    ("OBJECT_PEEHAT", "Peehat", "Peehat"),
    ("OBJECT_KINGDODONGO", "Kingdodongo", "Kingdodongo"),
    ("OBJECT_HORSE", "Horse", "Horse"),
    ("OBJECT_ZF", "Zf", "Zf"),
    ("OBJECT_GOMA", "Goma", "Goma"),
    ("OBJECT_ZL1", "Zl1", "Zl1"),
    ("OBJECT_GOL", "Gol", "Gol"),
    ("OBJECT_DODOJR", "Dodojr", "Dodojr"),
    ("OBJECT_TORCH2", "Torch2", "Torch2"),
    ("OBJECT_BL", "Bl", "Bl"),
    ("OBJECT_TP", "Tp", "Tp"),
    ("OBJECT_OA1", "Oa1", "Oa1"),
    ("OBJECT_ST", "St", "St"),
    ("OBJECT_BW", "Bw", "Bw"),
    ("OBJECT_EI", "Ei", "Ei"),
    ("OBJECT_HORSE_NORMAL", "Horse Normal", "Horse Normal"),
    ("OBJECT_OB1", "Ob1", "Ob1"),
    ("OBJECT_O_ANIME", "O Anime", "O Anime"),
    ("OBJECT_SPOT04_OBJECTS", "Spot04 Objects", "Spot04 Objects"),
    ("OBJECT_DDAN_OBJECTS", "Ddan Objects", "Ddan Objects"),
    ("OBJECT_HIDAN_OBJECTS", "Hidan Objects", "Hidan Objects"),
    ("OBJECT_HORSE_GANON", "Horse Ganon", "Horse Ganon"),
    ("OBJECT_OA2", "Oa2", "Oa2"),
    ("OBJECT_SPOT00_OBJECTS", "Spot00 Objects", "Spot00 Objects"),
    ("OBJECT_MB", "Mb", "Mb"),
    ("OBJECT_BOMBF", "Bombf", "Bombf"),
    ("OBJECT_SK2", "Sk2", "Sk2"),
    ("OBJECT_OE1", "Oe1", "Oe1"),
    ("OBJECT_OE_ANIME", "Oe Anime", "Oe Anime"),
    ("OBJECT_OE2", "Oe2", "Oe2"),
    ("OBJECT_YDAN_OBJECTS", "Ydan Objects", "Ydan Objects"),
    ("OBJECT_GND", "Gnd", "Gnd"),
    ("OBJECT_AM", "Am", "Am"),
    ("OBJECT_DEKUBABA", "Dekubaba", "Dekubaba"),
    ("OBJECT_OA3", "Oa3", "Oa3"),
    ("OBJECT_OA4", "Oa4", "Oa4"),
    ("OBJECT_OA5", "Oa5", "Oa5"),
    ("OBJECT_OA6", "Oa6", "Oa6"),
    ("OBJECT_OA7", "Oa7", "Oa7"),
    ("OBJECT_JJ", "Jj", "Jj"),
    ("OBJECT_OA8", "Oa8", "Oa8"),
    ("OBJECT_OA9", "Oa9", "Oa9"),
    ("OBJECT_OB2", "Ob2", "Ob2"),
    ("OBJECT_OB3", "Ob3", "Ob3"),
    ("OBJECT_OB4", "Ob4", "Ob4"),
    ("OBJECT_HORSE_ZELDA", "Horse Zelda", "Horse Zelda"),
    ("OBJECT_OPENING_DEMO1", "Opening Demo1", "Opening Demo1"),
    ("OBJECT_WARP1", "Warp1", "Warp1"),
    ("OBJECT_B_HEART", "B Heart", "B Heart"),
    ("OBJECT_DEKUNUTS", "Dekunuts", "Dekunuts"),
    ("OBJECT_OE3", "Oe3", "Oe3"),
    ("OBJECT_OE4", "Oe4", "Oe4"),
    ("OBJECT_MENKURI_OBJECTS", "Menkuri Objects", "Menkuri Objects"),
    ("OBJECT_OE5", "Oe5", "Oe5"),
    ("OBJECT_OE6", "Oe6", "Oe6"),
    ("OBJECT_OE7", "Oe7", "Oe7"),
    ("OBJECT_OE8", "Oe8", "Oe8"),
    ("OBJECT_OE9", "Oe9", "Oe9"),
    ("OBJECT_OE10", "Oe10", "Oe10"),
    ("OBJECT_OE11", "Oe11", "Oe11"),
    ("OBJECT_OE12", "Oe12", "Oe12"),
    ("OBJECT_VALI", "Vali", "Vali"),
    ("OBJECT_OA10", "Oa10", "Oa10"),
    ("OBJECT_OA11", "Oa11", "Oa11"),
    ("OBJECT_MIZU_OBJECTS", "Mizu Objects", "Mizu Objects"),
    ("OBJECT_FHG", "Fhg", "Fhg"),
    ("OBJECT_OSSAN", "Ossan", "Ossan"),
    ("OBJECT_MORI_HINERI1", "Mori Hineri1", "Mori Hineri1"),
    ("OBJECT_BB", "Bb", "Bb"),
    ("OBJECT_TOKI_OBJECTS", "Toki Objects", "Toki Objects"),
    ("OBJECT_YUKABYUN", "Yukabyun", "Yukabyun"),
    ("OBJECT_ZL2", "Zl2", "Zl2"),
    ("OBJECT_MJIN", "Mjin", "Mjin"),
    ("OBJECT_MJIN_FLASH", "Mjin Flash", "Mjin Flash"),
    ("OBJECT_MJIN_DARK", "Mjin Dark", "Mjin Dark"),
    ("OBJECT_MJIN_FLAME", "Mjin Flame", "Mjin Flame"),
    ("OBJECT_MJIN_ICE", "Mjin Ice", "Mjin Ice"),
    ("OBJECT_MJIN_SOUL", "Mjin Soul", "Mjin Soul"),
    ("OBJECT_MJIN_WIND", "Mjin Wind", "Mjin Wind"),
    ("OBJECT_MJIN_OKA", "Mjin Oka", "Mjin Oka"),
    ("OBJECT_HAKA_OBJECTS", "Haka Objects", "Haka Objects"),
    ("OBJECT_SPOT06_OBJECTS", "Spot06 Objects", "Spot06 Objects"),
    ("OBJECT_ICE_OBJECTS", "Ice Objects", "Ice Objects"),
    ("OBJECT_RELAY_OBJECTS", "Relay Objects", "Relay Objects"),
    ("OBJECT_PO_FIELD", "Po Field", "Po Field"),
    ("OBJECT_PO_COMPOSER", "Po Composer", "Po Composer"),
    ("OBJECT_MORI_HINERI1A", "Mori Hineri1a", "Mori Hineri1a"),
    ("OBJECT_MORI_HINERI2", "Mori Hineri2", "Mori Hineri2"),
    ("OBJECT_MORI_HINERI2A", "Mori Hineri2a", "Mori Hineri2a"),
    ("OBJECT_MORI_OBJECTS", "Mori Objects", "Mori Objects"),
    ("OBJECT_MORI_TEX", "Mori Tex", "Mori Tex"),
    ("OBJECT_SPOT08_OBJ", "Spot08 Obj", "Spot08 Obj"),
    ("OBJECT_WARP2", "Warp2", "Warp2"),
    ("OBJECT_HATA", "Hata", "Hata"),
    ("OBJECT_BIRD", "Bird", "Bird"),
    ("OBJECT_WOOD02", "Wood02", "Wood02"),
    ("OBJECT_LIGHTBOX", "Lightbox", "Lightbox"),
    ("OBJECT_PU_BOX", "Pu Box", "Pu Box"),
    ("OBJECT_TRAP", "Trap", "Trap"),
    ("OBJECT_VASE", "Vase", "Vase"),
    ("OBJECT_IM", "Im", "Im"),
    ("OBJECT_TA", "Ta", "Ta"),
    ("OBJECT_TK", "Tk", "Tk"),
    ("OBJECT_XC", "Xc", "Xc"),
    ("OBJECT_VM", "Vm", "Vm"),
    ("OBJECT_BV", "Bv", "Bv"),
    ("OBJECT_HAKACH_OBJECTS", "Hakach Objects", "Hakach Objects"),
    ("OBJECT_EFC_CRYSTAL_LIGHT", "Efc Crystal Light", "Efc Crystal Light"),
    ("OBJECT_EFC_FIRE_BALL", "Efc Fire Ball", "Efc Fire Ball"),
    ("OBJECT_EFC_FLASH", "Efc Flash", "Efc Flash"),
    ("OBJECT_EFC_LGT_SHOWER", "Efc Lgt Shower", "Efc Lgt Shower"),
    ("OBJECT_EFC_STAR_FIELD", "Efc Star Field", "Efc Star Field"),
    ("OBJECT_GOD_LGT", "God Lgt", "God Lgt"),
    ("OBJECT_LIGHT_RING", "Light Ring", "Light Ring"),
    ("OBJECT_TRIFORCE_SPOT", "Triforce Spot", "Triforce Spot"),
    ("OBJECT_BDAN_OBJECTS", "Bdan Objects", "Bdan Objects"),
    ("OBJECT_SD", "Sd", "Sd"),
    ("OBJECT_RD", "Rd", "Rd"),
    ("OBJECT_PO_SISTERS", "Po Sisters", "Po Sisters"),
    ("OBJECT_HEAVY_OBJECT", "Heavy Object", "Heavy Object"),
    ("OBJECT_GNDD", "Gndd", "Gndd"),
    ("OBJECT_FD", "Fd", "Fd"),
    ("OBJECT_DU", "Du", "Du"),
    ("OBJECT_FW", "Fw", "Fw"),
    ("OBJECT_MEDAL", "Medal", "Medal"),
    ("OBJECT_HORSE_LINK_CHILD", "Horse Link Child", "Horse Link Child"),
    ("OBJECT_SPOT02_OBJECTS", "Spot02 Objects", "Spot02 Objects"),
    ("OBJECT_HAKA", "Haka", "Haka"),
    ("OBJECT_RU1", "Ru1", "Ru1"),
    ("OBJECT_SYOKUDAI", "Syokudai", "Syokudai"),
    ("OBJECT_FD2", "Fd2", "Fd2"),
    ("OBJECT_DH", "Dh", "Dh"),
    ("OBJECT_RL", "Rl", "Rl"),
    ("OBJECT_EFC_TW", "Efc Tw", "Efc Tw"),
    ("OBJECT_DEMO_TRE_LGT", "Demo Tre Lgt", "Demo Tre Lgt"),
    ("OBJECT_GI_KEY", "Gi Key", "Gi Key"),
    ("OBJECT_MIR_RAY", "Mir Ray", "Mir Ray"),
    ("OBJECT_BROB", "Brob", "Brob"),
    ("OBJECT_GI_JEWEL", "Gi Jewel", "Gi Jewel"),
    ("OBJECT_SPOT09_OBJ", "Spot09 Obj", "Spot09 Obj"),
    ("OBJECT_SPOT18_OBJ", "Spot18 Obj", "Spot18 Obj"),
    ("OBJECT_BDOOR", "Bdoor", "Bdoor"),
    ("OBJECT_SPOT17_OBJ", "Spot17 Obj", "Spot17 Obj"),
    ("OBJECT_SHOP_DUNGEN", "Shop Dungen", "Shop Dungen"),
    ("OBJECT_NB", "Nb", "Nb"),
    ("OBJECT_MO", "Mo", "Mo"),
    ("OBJECT_SB", "Sb", "Sb"),
    ("OBJECT_GI_MELODY", "Gi Melody", "Gi Melody"),
    ("OBJECT_GI_HEART", "Gi Heart", "Gi Heart"),
    ("OBJECT_GI_COMPASS", "Gi Compass", "Gi Compass"),
    ("OBJECT_GI_BOSSKEY", "Gi Bosskey", "Gi Bosskey"),
    ("OBJECT_GI_MEDAL", "Gi Medal", "Gi Medal"),
    ("OBJECT_GI_NUTS", "Gi Nuts", "Gi Nuts"),
    ("OBJECT_SA", "Sa", "Sa"),
    ("OBJECT_GI_HEARTS", "Gi Hearts", "Gi Hearts"),
    ("OBJECT_GI_ARROWCASE", "Gi Arrowcase", "Gi Arrowcase"),
    ("OBJECT_GI_BOMBPOUCH", "Gi Bombpouch", "Gi Bombpouch"),
    ("OBJECT_IN", "In", "In"),
    ("OBJECT_TR", "Tr", "Tr"),
    ("OBJECT_SPOT16_OBJ", "Spot16 Obj", "Spot16 Obj"),
    ("OBJECT_OE1S", "Oe1s", "Oe1s"),
    ("OBJECT_OE4S", "Oe4s", "Oe4s"),
    ("OBJECT_OS_ANIME", "Os Anime", "Os Anime"),
    ("OBJECT_GI_BOTTLE", "Gi Bottle", "Gi Bottle"),
    ("OBJECT_GI_STICK", "Gi Stick", "Gi Stick"),
    ("OBJECT_GI_MAP", "Gi Map", "Gi Map"),
    ("OBJECT_OF1D_MAP", "Of1d Map", "Of1d Map"),
    ("OBJECT_RU2", "Ru2", "Ru2"),
    ("OBJECT_GI_SHIELD_1", "Gi Shield 1", "Gi Shield 1"),
    ("OBJECT_DEKUJR", "Dekujr", "Dekujr"),
    ("OBJECT_GI_MAGICPOT", "Gi Magicpot", "Gi Magicpot"),
    ("OBJECT_GI_BOMB_1", "Gi Bomb 1", "Gi Bomb 1"),
    ("OBJECT_OF1S", "Of1s", "Of1s"),
    ("OBJECT_MA2", "Ma2", "Ma2"),
    ("OBJECT_GI_PURSE", "Gi Purse", "Gi Purse"),
    ("OBJECT_HNI", "Hni", "Hni"),
    ("OBJECT_TW", "Tw", "Tw"),
    ("OBJECT_RR", "Rr", "Rr"),
    ("OBJECT_BXA", "Bxa", "Bxa"),
    ("OBJECT_ANUBICE", "Anubice", "Anubice"),
    ("OBJECT_GI_GERUDO", "Gi Gerudo", "Gi Gerudo"),
    ("OBJECT_GI_ARROW", "Gi Arrow", "Gi Arrow"),
    ("OBJECT_GI_BOMB_2", "Gi Bomb 2", "Gi Bomb 2"),
    ("OBJECT_GI_EGG", "Gi Egg", "Gi Egg"),
    ("OBJECT_GI_SCALE", "Gi Scale", "Gi Scale"),
    ("OBJECT_GI_SHIELD_2", "Gi Shield 2", "Gi Shield 2"),
    ("OBJECT_GI_HOOKSHOT", "Gi Hookshot", "Gi Hookshot"),
    ("OBJECT_GI_OCARINA", "Gi Ocarina", "Gi Ocarina"),
    ("OBJECT_GI_MILK", "Gi Milk", "Gi Milk"),
    ("OBJECT_MA1", "Ma1", "Ma1"),
    ("OBJECT_GANON", "Ganon", "Ganon"),
    ("OBJECT_SST", "Sst", "Sst"),
    ("OBJECT_NY_UNUSED", "Ny Unused", "Ny Unused"),
    ("OBJECT_NY", "Ny", "Ny"),
    ("OBJECT_FR", "Fr", "Fr"),
    ("OBJECT_GI_PACHINKO", "Gi Pachinko", "Gi Pachinko"),
    ("OBJECT_GI_BOOMERANG", "Gi Boomerang", "Gi Boomerang"),
    ("OBJECT_GI_BOW", "Gi Bow", "Gi Bow"),
    ("OBJECT_GI_GLASSES", "Gi Glasses", "Gi Glasses"),
    ("OBJECT_GI_LIQUID", "Gi Liquid", "Gi Liquid"),
    ("OBJECT_ANI", "Ani", "Ani"),
    ("OBJECT_DEMO_6K", "Demo 6k", "Demo 6k"),
    ("OBJECT_GI_SHIELD_3", "Gi Shield 3", "Gi Shield 3"),
    ("OBJECT_GI_LETTER", "Gi Letter", "Gi Letter"),
    ("OBJECT_SPOT15_OBJ", "Spot15 Obj", "Spot15 Obj"),
    ("OBJECT_JYA_OBJ", "Jya Obj", "Jya Obj"),
    ("OBJECT_GI_CLOTHES", "Gi Clothes", "Gi Clothes"),
    ("OBJECT_GI_BEAN", "Gi Bean", "Gi Bean"),
    ("OBJECT_GI_FISH", "Gi Fish", "Gi Fish"),
    ("OBJECT_GI_SAW", "Gi Saw", "Gi Saw"),
    ("OBJECT_GI_HAMMER", "Gi Hammer", "Gi Hammer"),
    ("OBJECT_GI_GRASS", "Gi Grass", "Gi Grass"),
    ("OBJECT_GI_LONGSWORD", "Gi Longsword", "Gi Longsword"),
    ("OBJECT_SPOT01_OBJECTS", "Spot01 Objects", "Spot01 Objects"),
    ("OBJECT_MD_UNUSED", "Md Unused", "Md Unused"),
    ("OBJECT_MD", "Md", "Md"),
    ("OBJECT_KM1", "Km1", "Km1"),
    ("OBJECT_KW1", "Kw1", "Kw1"),
    ("OBJECT_ZO", "Zo", "Zo"),
    ("OBJECT_KZ", "Kz", "Kz"),
    ("OBJECT_UMAJUMP", "Umajump", "Umajump"),
    ("OBJECT_MASTERKOKIRI", "Masterkokiri", "Masterkokiri"),
    ("OBJECT_MASTERKOKIRIHEAD", "Masterkokirihead", "Masterkokirihead"),
    ("OBJECT_MASTERGOLON", "Mastergolon", "Mastergolon"),
    ("OBJECT_MASTERZOORA", "Masterzoora", "Masterzoora"),
    ("OBJECT_AOB", "Aob", "Aob"),
    ("OBJECT_IK", "Ik", "Ik"),
    ("OBJECT_AHG", "Ahg", "Ahg"),
    ("OBJECT_CNE", "Cne", "Cne"),
    ("OBJECT_GI_NIWATORI", "Gi Niwatori", "Gi Niwatori"),
    ("OBJECT_SKJ", "Skj", "Skj"),
    ("OBJECT_GI_BOTTLE_LETTER", "Gi Bottle Letter", "Gi Bottle Letter"),
    ("OBJECT_BJI", "Bji", "Bji"),
    ("OBJECT_BBA", "Bba", "Bba"),
    ("OBJECT_GI_OCARINA_0", "Gi Ocarina 0", "Gi Ocarina 0"),
    ("OBJECT_DS", "Ds", "Ds"),
    ("OBJECT_ANE", "Ane", "Ane"),
    ("OBJECT_BOJ", "Boj", "Boj"),
    ("OBJECT_SPOT03_OBJECT", "Spot03 Object", "Spot03 Object"),
    ("OBJECT_SPOT07_OBJECT", "Spot07 Object", "Spot07 Object"),
    ("OBJECT_FZ", "Fz", "Fz"),
    ("OBJECT_BOB", "Bob", "Bob"),
    ("OBJECT_GE1", "Ge1", "Ge1"),
    ("OBJECT_YABUSAME_POINT", "Yabusame Point", "Yabusame Point"),
    ("OBJECT_GI_BOOTS_2", "Gi Boots 2", "Gi Boots 2"),
    ("OBJECT_GI_SEED", "Gi Seed", "Gi Seed"),
    ("OBJECT_GND_MAGIC", "Gnd Magic", "Gnd Magic"),
    ("OBJECT_D_ELEVATOR", "D Elevator", "D Elevator"),
    ("OBJECT_D_HSBLOCK", "D Hsblock", "D Hsblock"),
    ("OBJECT_D_LIFT", "D Lift", "D Lift"),
    ("OBJECT_MAMENOKI", "Mamenoki", "Mamenoki"),
    ("OBJECT_GOROIWA", "Goroiwa", "Goroiwa"),
    ("OBJECT_TORYO", "Toryo", "Toryo"),
    ("OBJECT_DAIKU", "Daiku", "Daiku"),
    ("OBJECT_NWC", "Nwc", "Nwc"),
    ("OBJECT_BLKOBJ", "Blkobj", "Blkobj"),
    ("OBJECT_GM", "Gm", "Gm"),
    ("OBJECT_MS", "Ms", "Ms"),
    ("OBJECT_HS", "Hs", "Hs"),
    ("OBJECT_INGATE", "Ingate", "Ingate"),
    ("OBJECT_LIGHTSWITCH", "Lightswitch", "Lightswitch"),
    ("OBJECT_KUSA", "Kusa", "Kusa"),
    ("OBJECT_TSUBO", "Tsubo", "Tsubo"),
    ("OBJECT_GI_GLOVES", "Gi Gloves", "Gi Gloves"),
    ("OBJECT_GI_COIN", "Gi Coin", "Gi Coin"),
    ("OBJECT_KANBAN", "Kanban", "Kanban"),
    ("OBJECT_GJYO_OBJECTS", "Gjyo Objects", "Gjyo Objects"),
    ("OBJECT_OWL", "Owl", "Owl"),
    ("OBJECT_MK", "Mk", "Mk"),
    ("OBJECT_FU", "Fu", "Fu"),
    ("OBJECT_GI_KI_TAN_MASK", "Gi Ki Tan Mask", "Gi Ki Tan Mask"),
    ("OBJECT_GI_REDEAD_MASK", "Gi Redead Mask", "Gi Redead Mask"),
    ("OBJECT_GI_SKJ_MASK", "Gi Skj Mask", "Gi Skj Mask"),
    ("OBJECT_GI_RABIT_MASK", "Gi Rabit Mask", "Gi Rabit Mask"),
    ("OBJECT_GI_TRUTH_MASK", "Gi Truth Mask", "Gi Truth Mask"),
    ("OBJECT_GANON_OBJECTS", "Ganon Objects", "Ganon Objects"),
    ("OBJECT_SIOFUKI", "Siofuki", "Siofuki"),
    ("OBJECT_STREAM", "Stream", "Stream"),
    ("OBJECT_MM", "Mm", "Mm"),
    ("OBJECT_FA", "Fa", "Fa"),
    ("OBJECT_OS", "Os", "Os"),
    ("OBJECT_GI_EYE_LOTION", "Gi Eye Lotion", "Gi Eye Lotion"),
    ("OBJECT_GI_POWDER", "Gi Powder", "Gi Powder"),
    ("OBJECT_GI_MUSHROOM", "Gi Mushroom", "Gi Mushroom"),
    ("OBJECT_GI_TICKETSTONE", "Gi Ticketstone", "Gi Ticketstone"),
    ("OBJECT_GI_BROKENSWORD", "Gi Brokensword", "Gi Brokensword"),
    ("OBJECT_JS", "Js", "Js"),
    ("OBJECT_CS", "Cs", "Cs"),
    ("OBJECT_GI_PRESCRIPTION", "Gi Prescription", "Gi Prescription"),
    ("OBJECT_GI_BRACELET", "Gi Bracelet", "Gi Bracelet"),
    ("OBJECT_GI_SOLDOUT", "Gi Soldout", "Gi Soldout"),
    ("OBJECT_GI_FROG", "Gi Frog", "Gi Frog"),
    ("OBJECT_MAG", "Mag", "Mag"),
    ("OBJECT_DOOR_GERUDO", "Door Gerudo", "Door Gerudo"),
    ("OBJECT_GT", "Gt", "Gt"),
    ("OBJECT_EFC_ERUPC", "Efc Erupc", "Efc Erupc"),
    ("OBJECT_ZL2_ANIME1", "Zl2 Anime1", "Zl2 Anime1"),
    ("OBJECT_ZL2_ANIME2", "Zl2 Anime2", "Zl2 Anime2"),
    ("OBJECT_GI_GOLONMASK", "Gi Golonmask", "Gi Golonmask"),
    ("OBJECT_GI_ZORAMASK", "Gi Zoramask", "Gi Zoramask"),
    ("OBJECT_GI_GERUDOMASK", "Gi Gerudomask", "Gi Gerudomask"),
    ("OBJECT_GANON2", "Ganon2", "Ganon2"),
    ("OBJECT_KA", "Ka", "Ka"),
    ("OBJECT_TS", "Ts", "Ts"),
    ("OBJECT_ZG", "Zg", "Zg"),
    ("OBJECT_GI_HOVERBOOTS", "Gi Hoverboots", "Gi Hoverboots"),
    ("OBJECT_GI_M_ARROW", "Gi M Arrow", "Gi M Arrow"),
    ("OBJECT_DS2", "Ds2", "Ds2"),
    ("OBJECT_EC", "Ec", "Ec"),
    ("OBJECT_FISH", "Fish", "Fish"),
    ("OBJECT_GI_SUTARU", "Gi Sutaru", "Gi Sutaru"),
    ("OBJECT_GI_GODDESS", "Gi Goddess", "Gi Goddess"),
    ("OBJECT_SSH", "Ssh", "Ssh"),
    ("OBJECT_BIGOKUTA", "Bigokuta", "Bigokuta"),
    ("OBJECT_BG", "Bg", "Bg"),
    ("OBJECT_SPOT05_OBJECTS", "Spot05 Objects", "Spot05 Objects"),
    ("OBJECT_SPOT12_OBJ", "Spot12 Obj", "Spot12 Obj"),
    ("OBJECT_BOMBIWA", "Bombiwa", "Bombiwa"),
    ("OBJECT_HINTNUTS", "Hintnuts", "Hintnuts"),
    ("OBJECT_RS", "Rs", "Rs"),
    ("OBJECT_SPOT00_BREAK", "Spot00 Break", "Spot00 Break"),
    ("OBJECT_GLA", "Gla", "Gla"),
    ("OBJECT_SHOPNUTS", "Shopnuts", "Shopnuts"),
    ("OBJECT_GELDB", "Geldb", "Geldb"),
    ("OBJECT_GR", "Gr", "Gr"),
    ("OBJECT_DOG", "Dog", "Dog"),
    ("OBJECT_JYA_IRON", "Jya Iron", "Jya Iron"),
    ("OBJECT_JYA_DOOR", "Jya Door", "Jya Door"),
    ("OBJECT_SPOT11_OBJ", "Spot11 Obj", "Spot11 Obj"),
    ("OBJECT_KIBAKO2", "Kibako2", "Kibako2"),
    ("OBJECT_DNS", "Dns", "Dns"),
    ("OBJECT_DNK", "Dnk", "Dnk"),
    ("OBJECT_GI_FIRE", "Gi Fire", "Gi Fire"),
    ("OBJECT_GI_INSECT", "Gi Insect", "Gi Insect"),
    ("OBJECT_GI_BUTTERFLY", "Gi Butterfly", "Gi Butterfly"),
    ("OBJECT_GI_GHOST", "Gi Ghost", "Gi Ghost"),
    ("OBJECT_GI_SOUL", "Gi Soul", "Gi Soul"),
    ("OBJECT_BOWL", "Bowl", "Bowl"),
    ("OBJECT_DEMO_KEKKAI", "Demo Kekkai", "Demo Kekkai"),
    ("OBJECT_EFC_DOUGHNUT", "Efc Doughnut", "Efc Doughnut"),
    ("OBJECT_GI_DEKUPOUCH", "Gi Dekupouch", "Gi Dekupouch"),
    ("OBJECT_GANON_ANIME1", "Ganon Anime1", "Ganon Anime1"),
    ("OBJECT_GANON_ANIME2", "Ganon Anime2", "Ganon Anime2"),
    ("OBJECT_GANON_ANIME3", "Ganon Anime3", "Ganon Anime3"),
    ("OBJECT_GI_RUPY", "Gi Rupy", "Gi Rupy"),
    ("OBJECT_SPOT01_MATOYA", "Spot01 Matoya", "Spot01 Matoya"),
    ("OBJECT_SPOT01_MATOYAB", "Spot01 Matoyab", "Spot01 Matoyab"),
    ("OBJECT_MU", "Mu", "Mu"),
    ("OBJECT_WF", "Wf", "Wf"),
    ("OBJECT_SKB", "Skb", "Skb"),
    ("OBJECT_GJ", "Gj", "Gj"),
    ("OBJECT_GEFF", "Geff", "Geff"),
    ("OBJECT_HAKA_DOOR", "Haka Door", "Haka Door"),
    ("OBJECT_GS", "Gs", "Gs"),
    ("OBJECT_PS", "Ps", "Ps"),
    ("OBJECT_BWALL", "Bwall", "Bwall"),
    ("OBJECT_COW", "Cow", "Cow"),
    ("OBJECT_COB", "Cob", "Cob"),
    ("OBJECT_GI_SWORD_1", "Gi Sword 1", "Gi Sword 1"),
    ("OBJECT_DOOR_KILLER", "Door Killer", "Door Killer"),
    ("OBJECT_OUKE_HAKA", "Ouke Haka", "Ouke Haka"),
    ("OBJECT_TIMEBLOCK", "Timeblock", "Timeblock"),
]

# see curRoom.unk_03
ootEnumRoomBehaviour = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "Default", "Default"),
    ("0x01", "Dungeon Behavior (Z-Target, Sun's Song)", "Dungeon Behavior (Z-Target, Sun's Song)"),
    ("0x02", "Disable Backflips/Sidehops", "Disable Backflips/Sidehops"),
    ("0x03", "Disable Color Dither", "Disable Color Dither"),
    ("0x04", "(?) Horse Camera Related", "(?) Horse Camera Related"),
    ("0x05", "Disable Darker Screen Effect (NL/Spins)", "Disable Darker Screen Effect (NL/Spins)"),
]
