ootEnumSceneMenu = [
    ("General", "General", "General"),
    ("Lighting", "Lighting", "Lighting"),
    ("Cutscene", "Cutscene", "Cutscene"),
    ("Exits", "Exits", "Exits"),
    ("Alternate", "Alternate", "Alternate"),
]

ootEnumSceneMenuAlternate = [
    ("General", "General", "General"),
    ("Lighting", "Lighting", "Lighting"),
    ("Cutscene", "Cutscene", "Cutscene"),
]

ootEnumLightGroupMenu = [
    ("Dawn", "Dawn", "Dawn"),
    ("Day", "Day", "Day"),
    ("Dusk", "Dusk", "Dusk"),
    ("Night", "Night", "Night"),
]

ootEnumCloudiness = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "Sunny", "Sunny"),
    ("0x01", "Cloudy", "Cloudy"),
]

ootEnumCameraMode = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "Default", "Default"),
    ("0x10", "Two Views, No C-Up", "Two Views, No C-Up"),
    ("0x20", "Rotating Background, Bird's Eye C-Up", "Rotating Background, Bird's Eye C-Up"),
    ("0x30", "Fixed Background, No C-Up", "Fixed Background, No C-Up"),
    ("0x40", "Rotating Background, No C-Up", "Rotating Background, No C-Up"),
    ("0x50", "Shooting Gallery", "Shooting Gallery"),
]

ootEnumMapLocation = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "Hyrule Field", "Hyrule Field"),
    ("0x01", "Kakariko Village", "Kakariko Village"),
    ("0x02", "Graveyard", "Graveyard"),
    ("0x03", "Zora's River", "Zora's River"),
    ("0x04", "Kokiri Forest", "Kokiri Forest"),
    ("0x05", "Sacred Forest Meadow", "Sacred Forest Meadow"),
    ("0x06", "Lake Hylia", "Lake Hylia"),
    ("0x07", "Zora's Domain", "Zora's Domain"),
    ("0x08", "Zora's Fountain", "Zora's Fountain"),
    ("0x09", "Gerudo Valley", "Gerudo Valley"),
    ("0x0A", "Lost Woods", "Lost Woods"),
    ("0x0B", "Desert Colossus", "Desert Colossus"),
    ("0x0C", "Gerudo's Fortress", "Gerudo's Fortress"),
    ("0x0D", "Haunted Wasteland", "Haunted Wasteland"),
    ("0x0E", "Market", "Market"),
    ("0x0F", "Hyrule Castle", "Hyrule Castle"),
    ("0x10", "Death Mountain Trail", "Death Mountain Trail"),
    ("0x11", "Death Mountain Crater", "Death Mountain Crater"),
    ("0x12", "Goron City", "Goron City"),
    ("0x13", "Lon Lon Ranch", "Lon Lon Ranch"),
    ("0x14", "Dampe's Grave & Windmill", "Dampe's Grave & Windmill"),
    ("0x15", "Ganon's Castle", "Ganon's Castle"),
    ("0x16", "Grottos & Fairy Fountains", "Grottos & Fairy Fountains"),
]

ootEnumSkybox = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "None", "None"),
    ("0x01", "Standard Sky", "Standard Sky"),
    ("0x02", "Hylian Bazaar", "Hylian Bazaar"),
    ("0x03", "Brown Cloudy Sky", "Brown Cloudy Sky"),
    ("0x04", "Market Ruins", "Market Ruins"),
    ("0x05", "Black Cloudy Night", "Black Cloudy Night"),
    ("0x07", "Link's House", "Link's House"),
    ("0x09", "Market (Main Square, Day)", "Market (Main Square, Day)"),
    ("0x0A", "Market (Main Square, Night)", "Market (Main Square, Night)"),
    ("0x0B", "Happy Mask Shop", "Happy Mask Shop"),
    ("0x0C", "Know-It-All Brothers' House", "Know-It-All Brothers' House"),
    ("0x0E", "Kokiri Twins' House", "Kokiri Twins' House"),
    ("0x0F", "Stable", "Stable"),
    ("0x10", "Stew Lady's House", "Stew Lady's House"),
    ("0x11", "Kokiri Shop", "Kokiri Shop"),
    ("0x13", "Goron Shop", "Goron Shop"),
    ("0x14", "Zora Shop", "Zora Shop"),
    ("0x16", "Kakariko Potions Shop", "Kakariko Potions Shop"),
    ("0x17", "Hylian Potions Shop", "Hylian Potions Shop"),
    ("0x18", "Bomb Shop", "Bomb Shop"),
    ("0x1A", "Dog Lady's House", "Dog Lady's House"),
    ("0x1B", "Impa's House", "Impa's House"),
    ("0x1C", "Gerudo Tent", "Gerudo Tent"),
    ("0x1D", "Environment Color", "Environment Color"),
    ("0x20", "Mido's House", "Mido's House"),
    ("0x21", "Saria's House", "Saria's House"),
    ("0x22", "Dog Guy's House", "Dog Guy's House"),
]

ootEnumSkyboxLighting = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "Time Of Day", "Time Of Day"),
    ("0x01", "Indoor", "Indoor"),
]

ootEnumAudioSessionPreset = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "0x00", "0x00"),
]

ootEnumMusicSeq = [
    ("Custom", "Custom", "Custom"),
    ("0x02", "Hyrule Field", "Hyrule Field"),
    ("0x03", "Hyrule Field (Initial Segment From Loading Area)", "Hyrule Field (Initial Segment From Loading Area)"),
    ("0x04", "Hyrule Field (Moving Segment 1)", "Hyrule Field (Moving Segment 1)"),
    ("0x05", "Hyrule Field (Moving Segment 2)", "Hyrule Field (Moving Segment 2)"),
    ("0x06", "Hyrule Field (Moving Segment 3)", "Hyrule Field (Moving Segment 3)"),
    ("0x07", "Hyrule Field (Moving Segment 4)", "Hyrule Field (Moving Segment 4)"),
    ("0x08", "Hyrule Field (Moving Segment 5)", "Hyrule Field (Moving Segment 5)"),
    ("0x09", "Hyrule Field (Moving Segment 6)", "Hyrule Field (Moving Segment 6)"),
    ("0x0A", "Hyrule Field (Moving Segment 7)", "Hyrule Field (Moving Segment 7)"),
    ("0x0B", "Hyrule Field (Moving Segment 8)", "Hyrule Field (Moving Segment 8)"),
    ("0x0C", "Hyrule Field (Moving Segment 9)", "Hyrule Field (Moving Segment 9)"),
    ("0x0D", "Hyrule Field (Moving Segment 10)", "Hyrule Field (Moving Segment 10)"),
    ("0x0E", "Hyrule Field (Moving Segment 11)", "Hyrule Field (Moving Segment 11)"),
    ("0x0F", "Hyrule Field (Enemy Approaches)", "Hyrule Field (Enemy Approaches)"),
    ("0x10", "Hyrule Field (Enemy Near Segment 1)", "Hyrule Field (Enemy Near Segment 1)"),
    ("0x11", "Hyrule Field (Enemy Near Segment 2)", "Hyrule Field (Enemy Near Segment 2)"),
    ("0x12", "Hyrule Field (Enemy Near Segment 3)", "Hyrule Field (Enemy Near Segment 3)"),
    ("0x13", "Hyrule Field (Enemy Near Segment 4)", "Hyrule Field (Enemy Near Segment 4)"),
    ("0x14", "Hyrule Field (Standing Still Segment 1)", "Hyrule Field (Standing Still Segment 1)"),
    ("0x15", "Hyrule Field (Standing Still Segment 2)", "Hyrule Field (Standing Still Segment 2)"),
    ("0x16", "Hyrule Field (Standing Still Segment 3)", "Hyrule Field (Standing Still Segment 3)"),
    ("0x17", "Hyrule Field (Standing Still Segment 4)", "Hyrule Field (Standing Still Segment 4)"),
    ("0x18", "Dodongo's Cavern", "Dodongo's Cavern"),
    ("0x19", "Kakariko Village (Adult)", "Kakariko Village (Adult)"),
    ("0x1A", "Enemy Battle", "Enemy Battle"),
    ("0x1B", "Boss Battle 00", "Boss Battle 00"),
    ("0x1C", "Inside the Deku Tree", "Inside the Deku Tree"),
    ("0x1D", "Market", "Market"),
    ("0x1E", "Title Theme", "Title Theme"),
    ("0x1F", "Link's House", "Link's House"),
    ("0x20", "Game Over", "Game Over"),
    ("0x21", "Boss Clear", "Boss Clear"),
    ("0x22", "Item Get", "Item Get"),
    ("0x23", "Opening Ganon", "Opening Ganon"),
    ("0x24", "Heart Get", "Heart Get"),
    ("0x25", "Prelude Of Light", "Prelude Of Light"),
    ("0x26", "Inside Jabu-Jabu's Belly", "Inside Jabu-Jabu's Belly"),
    ("0x27", "Kakariko Village (Child)", "Kakariko Village (Child)"),
    ("0x28", "Great Fairy's Fountain", "Great Fairy's Fountain"),
    ("0x29", "Zelda's Theme", "Zelda's Theme"),
    ("0x2A", "Fire Temple", "Fire Temple"),
    ("0x2B", "Open Treasure Chest", "Open Treasure Chest"),
    ("0x2C", "Forest Temple", "Forest Temple"),
    ("0x2D", "Hyrule Castle Courtyard", "Hyrule Castle Courtyard"),
    ("0x2E", "Ganondorf's Theme", "Ganondorf's Theme"),
    ("0x2F", "Lon Lon Ranch", "Lon Lon Ranch"),
    ("0x30", "Goron City", "Goron City "),
    ("0x31", "Hyrule Field Morning Theme", "Hyrule Field Morning Theme"),
    ("0x32", "Spiritual Stone Get", "Spiritual Stone Get"),
    ("0x33", "Bolero of Fire", "Bolero of Fire"),
    ("0x34", "Minuet of Woods", "Minuet of Woods"),
    ("0x35", "Serenade of Water", "Serenade of Water"),
    ("0x36", "Requiem of Spirit", "Requiem of Spirit"),
    ("0x37", "Nocturne of Shadow", "Nocturne of Shadow"),
    ("0x38", "Mini-Boss Battle", "Mini-Boss Battle"),
    ("0x39", "Obtain Small Item", "Obtain Small Item"),
    ("0x3A", "Temple of Time", "Temple of Time"),
    ("0x3B", "Escape from Lon Lon Ranch", "Escape from Lon Lon Ranch"),
    ("0x3C", "Kokiri Forest", "Kokiri Forest"),
    ("0x3D", "Obtain Fairy Ocarina", "Obtain Fairy Ocarina"),
    ("0x3E", "Lost Woods", "Lost Woods"),
    ("0x3F", "Spirit Temple", "Spirit Temple"),
    ("0x40", "Horse Race", "Horse Race"),
    ("0x41", "Horse Race Goal", "Horse Race Goal"),
    ("0x42", "Ingo's Theme", "Ingo's Theme"),
    ("0x43", "Obtain Medallion", "Obtain Medallion"),
    ("0x44", "Ocarina Saria's Song", "Ocarina Saria's Song"),
    ("0x45", "Ocarina Epona's Song", "Ocarina Epona's Song"),
    ("0x46", "Ocarina Zelda's Lullaby", "Ocarina Zelda's Lullaby"),
    ("0x47", "Sun's Song", "Sun's Song"),
    ("0x48", "Song of Time", "Song of Time"),
    ("0x49", "Song of Storms", "Song of Storms"),
    ("0x4A", "Fairy Flying", "Fairy Flying"),
    ("0x4B", "Deku Tree", "Deku Tree"),
    ("0x4C", "Windmill Hut", "Windmill Hut"),
    ("0x4D", "Legend of Hyrule", "Legend of Hyrule"),
    ("0x4E", "Shooting Gallery", "Shooting Gallery"),
    ("0x4F", "Sheik's Theme", "Sheik's Theme"),
    ("0x50", "Zora's Domain", "Zora's Domain"),
    ("0x51", "Enter Zelda", "Enter Zelda"),
    ("0x52", "Goodbye to Zelda", "Goodbye to Zelda"),
    ("0x53", "Master Sword", "Master Sword"),
    ("0x54", "Ganon Intro", "Ganon Intro"),
    ("0x55", "Shop", "Shop"),
    ("0x56", "Chamber of the Sages", "Chamber of the Sages"),
    ("0x57", "File Select", "File Select"),
    ("0x58", "Ice Cavern", "Ice Cavern"),
    ("0x59", "Open Door of Temple of Time", "Open Door of Temple of Time"),
    ("0x5A", "Kaepora Gaebora's Theme", "Kaepora Gaebora's Theme"),
    ("0x5B", "Shadow Temple", "Shadow Temple"),
    ("0x5C", "Water Temple", "Water Temple"),
    ("0x5D", "Ganon's Castle Bridge", "Ganon's Castle Bridge"),
    ("0x5E", "Ocarina of Time", "Ocarina of Time"),
    ("0x5F", "Gerudo Valley", "Gerudo Valley"),
    ("0x60", "Potion Shop", "Potion Shop"),
    ("0x61", "Kotake & Koume's Theme", "Kotake & Koume's Theme"),
    ("0x62", "Escape from Ganon's Castle", "Escape from Ganon's Castle"),
    ("0x63", "Ganon's Castle Under Ground", "Ganon's Castle Under Ground"),
    ("0x64", "Ganondorf Battle", "Ganondorf Battle"),
    ("0x65", "Ganon Battle", "Ganon Battle"),
    ("0x66", "Seal of Six Sages", "Seal of Six Sages"),
    ("0x67", "End Credits I", "End Credits I"),
    ("0x68", "End Credits II", "End Credits II"),
    ("0x69", "End Credits III", "End Credits III"),
    ("0x6A", "End Credits IV", "End Credits IV"),
    ("0x6B", "King Dodongo & Volvagia Boss Battle", "King Dodongo & Volvagia Boss Battle"),
    ("0x6C", "Mini-Game", "Mini-Game"),
]

ootEnumNightSeq = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "Standard night [day and night cycle]", "0x00"),
    ("0x01", "Standard night [Kakariko]", "0x01"),
    ("0x02", "Distant storm [Graveyard]", "0x02"),
    ("0x03", "Howling wind and cawing [Ganon's Castle]", "0x03"),
    ("0x04", "Wind + night birds [Kokiri]", "0x04"),
    ("0x05", "Wind + crickets", "0x05"),
    ("0x06", "Wind", "0x06"),
    ("0x07", "Howling wind", "0x07"),
    ("0x08", "Wind + crickets", "0x08"),
    ("0x09", "Wind + crickets", "0x09"),
    ("0x0A", "Tubed howling wind [Wasteland]", "0x0A"),
    ("0x0B", "Tubed howling wind [Colossus]", "0x0B"),
    ("0x0C", "Wind", "0x0C"),
    ("0x0D", "Wind + crickets", "0x0D"),
    ("0x0E", "Wind + crickets", "0x0E"),
    ("0x0F", "Wind + birds", "0x0F"),
    ("0x10", "Wind + crickets", "0x10"),
    ("0x11", "?", "0x11"),
    ("0x12", "Wind + crickets", "0x12"),
    ("0x13", "Day music always playing", "0x13"),
    ("0x14", "Silence", "0x14"),
    ("0x16", "Silence", "0x16"),
    ("0x17", "High tubed wind + rain", "0x17"),
    ("0x18", "Silence", "0x18"),
    ("0x19", "Silence", "0x19"),
    ("0x1A", "High tubed wind + rain", "0x1A"),
    ("0x1B", "Silence", "0x1B"),
    ("0x1C", "Rain", "0x1C"),
    ("0x1D", "High tubed wind + rain", "0x1D"),
    ("0x1E", "Silence", "0x1E"),
    ("0x1F", "High tubed wind + rain ", "0x1F"),
]

ootEnumGlobalObject = [
    ("Custom", "Custom", "Custom"),
    ("0x0000", "None", "None"),
    ("0x0002", "Overworld", "gameplay_field_keep"),
    ("0x0003", "Dungeon", "gameplay_dangeon_keep"),
]

ootEnumNaviHints = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "None", "None"),
    ("0x01", "Overworld", "elf_message_field"),
    ("0x02", "Dungeon", "elf_message_ydan"),
]

ootEnumTransitionAnims = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "Spiky", "Spiky"),
    ("0x01", "Triforce", "Triforce"),
    ("0x02", "Slow Black Fade", "Slow Black Fade"),
    ("0x03", "Slow Day/White, Slow Night/Black Fade", "Slow Day/White, Slow Night/Black Fade"),
    ("0x04", "Fast Day/Black, Slow Night/Black Fade", "Fast Day/Black, Slow Night/Black Fade"),
    ("0x05", "Fast Day/White, Slow Night/Black Fade", "Fast Day/White, Slow Night/Black Fade"),
    ("0x06", "Very Slow Day/White, Slow Night/Black Fade", "Very Slow Day/White, Slow Night/Black Fade"),
    ("0x07", "Very Slow Day/White, Slow Night/Black Fade", "Very Slow Day/White, Slow Night/Black Fade"),
    ("0x0E", "Slow Sandstorm Fade", "Slow Sandstorm Fade"),
    ("0x0F", "Fast Sandstorm Fade", "Fast Sandstorm Fade"),
    ("0x20", "Iris Fade", "Iris Fade"),
    ("0x2C", "Shortcut Transition", "Shortcut Transition"),
]

ootEnumExitIndex = [
    ("Custom", "Custom", "Custom"),
    ("Default", "Default", "Default"),
]

ootEnumCSWriteType = [
    ("Custom", "Custom", "Provide the name of a cutscene header variable"),
    ("Embedded", "Embedded", "Cutscene data is within scene header (deprecated)"),
    ("Object", "Object", "Reference to Blender object representing cutscene"),
]
